jQuery.noConflict();
var FeaturedSlideshow=Class.create({config:null,nextPane:null,currentPane:null,currentIndex:0,autoscrollTimer:null,currentAnimation:null,initialize:function(config){var self=this;this.config=$A(config);var firstItem=this.config[0];var nextItem=this.config[1%this.config.length];this.currentPane=$('w_fss_pane0');this.nextPane=$('w_fss_pane1');this.currentPane.select('.w-fss-image')[0].observe('load',function(event){self.aspectFillImage(event.element());});this.nextPane.select('.w-fss-image')[0].observe('load',function(event){self.aspectFillImage(event.element());});var clickHandler=function(){var item=self.config[self.currentIndex];window.location=item.url;}
var trackHandler=function(){var item=self.config[self.currentIndex];var url=item.url;var token='featured';var parts=url.split('?');var path=parts[0];path=path.toLowerCase().sub(/^\//,'').sub(/^https?:\/\/[^\/]*\//,'');var qs=$H({t:'st',f:token,to:path,k:Math.floor(Math.random()*1000000)}).toQueryString();
var img=new Element('img',{style:'position: absolute; left: -50000px; visibility: hidden;'});
$(document.body).insert({bottom:img});setTimeout(function(){img.remove()},100);}
this.nextPane.observe('click',clickHandler);this.currentPane.observe('click',clickHandler);this.nextPane.observe('mousedown',trackHandler);this.currentPane.observe('mousedown',trackHandler);this.nextPane.setStyle({left:this.currentPane.positionedOffset()[0]+this.currentPane.getWidth()+'px'});this.setPaneContent(this.currentPane,firstItem,false);$('w_fss').select('.w-fss-tmp')[0].writeAttribute('src',nextItem.image)
this.autoscrollTimer=setInterval(function(){self.displayNextPage();},7000);var indicators=$('w_fss').select('.w-fss-pageindicators')[0];var numPages=this.config.length;var indicatorsWidth=numPages*12+(numPages-1)*8;var indicatorLeft=(this.currentPane.getWidth()-indicatorsWidth)/2;for(var i=0;i<numPages;i++){var indicator=new Element('span');indicator.addClassName('w-fss-pageindicator');if(i==0){indicator.addClassName('w-fss-pageindicator-selected');}
indicator.setStyle({left:indicatorLeft+'px'});indicator.index=i;indicator.observe('click',function(event){if(self.autoscrollTimer){clearInterval(self.autoscrollTimer);self.autoscrollTimer=null;}
var elem=event.element();if(elem.index!=self.currentIndex){self.displayPageNumber(elem.index);}});indicator.observe('mouseover',function(event){event.element().addClassName('w-fss-pageindicator-selected');});indicator.observe('mouseout',function(event){var elem=event.element();if(elem.index!=self.currentIndex){elem.removeClassName('w-fss-pageindicator-selected');}});indicators.insert(indicator);indicatorLeft+=20;}
$('w_fss').select('.w-fss-leftarrow')[0].observe('click',function(){if(self.autoscrollTimer){clearInterval(self.autoscrollTimer);self.autoscrollTimer=null;}
self.displayPreviousPage(true);})
$('w_fss').select('.w-fss-rightarrow')[0].observe('click',function(){if(self.autoscrollTimer){clearInterval(self.autoscrollTimer);self.autoscrollTimer=null;}
self.displayNextPage(true);})},setPaneContent:function(pane,configitem,prepareToFadeIn){var img=pane.select('.w-fss-image')[0];img.setStyle({width:'auto',height:'auto'});img.writeAttribute('src',configitem.image);var overlay=pane.select('.w-fss-new')[0];if(configitem.overlay_image){overlay.writeAttribute('src',configitem.overlay_image);}else{overlay.writeAttribute('src','http://img1.ak.crunchyroll.com/i/blank.gif');}
pane.select('.w-fss-seriesname')[0].update(configitem.series_name.escapeHTML());pane.select('.w-fss-episodename')[0].update(configitem.media_name.escapeHTML());pane.select('.w-fss-description')[0].update(configitem.description.escapeHTML());if(prepareToFadeIn){pane.select('.w-fss-descbox')[0].hide();}},aspectFillImage:function(img){var width=img.getWidth();var height=img.getHeight();var paneWidth=this.currentPane.getWidth();var paneHeight=this.currentPane.getHeight();var aspect=width/height;if(aspect>=paneWidth/paneHeight){img.setStyle({width:aspect*paneHeight+'px',height:paneHeight+'px'});img.setStyle({left:(paneWidth-img.getWidth())/2+'px',top:0});}else{img.setStyle({width:paneWidth+'px',height:paneWidth/aspect+'px'});img.setStyle({left:0,top:(paneHeight-img.getHeight())/2+'px'});}},displayNextPage:function(forceDirection){var nextIndex=(this.currentIndex+1)%this.config.length;var direction=forceDirection?'right':null;this.displayPageNumber(nextIndex,direction);},displayPreviousPage:function(forceDirection){var prevIndex=(this.currentIndex+this.config.length-1)%this.config.length;var direction=forceDirection?'left':null;this.displayPageNumber(prevIndex,direction);},displayPageNumber:function(index,forceDirection){var item=this.config[index];var nextItem=this.config[(index+1)%this.config.length];if(this.currentAnimation){this.currentAnimation.cancel();}
var panels=$$('.w-fss-panes')[0];this.nextPane.setStyle({left:this.currentPane.getWidth()+'px'});this.currentPane.setStyle({left:'0px'});panels.setStyle({left:'0px'});this.setPaneContent(this.nextPane,item,true);var indicators=$('w_fss').select('.w-fss-pageindicator');for(var i=0;i<indicators.length;i++){var indicator=indicators[i];if(indicator.index==index){indicator.addClassName('w-fss-pageindicator-selected');}else{indicator.removeClassName('w-fss-pageindicator-selected');}}
var distanceToMove=this.currentPane.getWidth();var pane=this.nextPane;var finalLeft;var direction;if(forceDirection){direction=forceDirection;}else{direction=(index<this.currentIndex)?'left':'right';}
if(direction=='left'){this.nextPane.setStyle({left:this.currentPane.positionedOffset()[0]-this.currentPane.getWidth()+'px'});finalLeft=panels.positionedOffset()[0]+distanceToMove;}else{this.nextPane.setStyle({left:this.currentPane.positionedOffset()[0]+this.currentPane.getWidth()+'px'});finalLeft=panels.positionedOffset()[0]-distanceToMove;}
var self=this;var theNextPane=this.currentPane;this.currentAnimation=new Effect.Morph(panels,{style:{left:finalLeft+'px'},duration:0.3,afterFinish:function(){new Effect.Appear(pane.select('.w-fss-descbox')[0],{duration:0.3,delay:.3});$('w_fss').select('.w-fss-tmp')[0].writeAttribute('src',nextItem.image)
self.currentAnimation=null;}});var paneswaptmp=this.currentPane;this.currentPane=this.nextPane;this.nextPane=paneswaptmp;this.currentIndex=index;}});
eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('2(v).y(4(){2("#N").i(4(){2(n).l(2(n).l()==\'  \'?\' \':\'  \');j(2(n).l()==\'  \'){j(2.t.r){2("#b").3("q-p","-o")}2("#g").7(8,0,4(){2("#g").3("9","h");2("#g").3("6","f");2("#e").7(8,1);2("#e").3("9","d");2("#e").3("6","c")})}j(2(n).l()==\' \'){j(2.t.r){2("#b").3("q-p","-o")}2("#e").7(8,0,4(){2("#e").3("9","h");2("#e").3("6","f");2("#g").3("9","d");2("#g").3("6","c");2("#g").7(8,1)})}});2("#E").i(4(){2("#a").7(8,0,4(){2("#a").3("9","h");2("#a").3("6","f");2("#5").7(8,1);2("#5").3("9","d");2("#5").3("6","c")})});2("#w").i(4(){2("#5").7(8,0,4(){2("#5").3("9","h");2("#5").3("6","f");2("#a").3("9","d");2("#a").3("6","c");2("#a").7(8,1)})});2("#x").i(4(){2("#5").7(8,0,4(){2("#5").3("9","h");2("#5").3("6","f");2("#k").7(8,1);2("#k").3("9","d");2("#k").3("6","c")})});2("#z").i(4(){2("#k").7(8,0,4(){2("#u").3("9","h");2("#u").3("6","f");2("#5").7(8,1);2("#5").3("9","d");2("#5").3("6","c")})});2(\'.B\').C({D:\'s\'});2(\'.F\').G({H:I,J:0,K:"[L más]",M:"[A]",})});',50,50,'||jQuery|css|function|gendos|visibility|fadeTo|300|display|genuno||visible|block|dos|hidden|uno|none|click|if|gentres|text||this|65px|top|margin|msie||browser|gentre|document|dosuno|dostres|ready|tresdos|Ocultar|tip|tipsy|gravity|unodos|sinop|jTruncate|length|450|minTrail|moreText|Leer|lessText|id'.split('|'),0,{}))